# Stage 1: Build
FROM golang:1.25.1 AS builder
WORKDIR /app
ENV GO111MODULE=on CGO_ENABLED=0
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o s3worker ./cmd/worker/main.go

# Stage 2: Runtime
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/s3worker .

CMD ["./s3worker"]
